#!/bin/bash
### BEGIN INIT INFO
# Provides:          mailgraph
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mailgraph
# Description:       mailgraph mailgraph mailgraph
### END INIT INFO

(( EUID )) && echo .You need to have root priviliges.. && exit 1


# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

NAME=Mailgraph
PATH=/bin:/usr/bin
MAILGRAPH_PL=/usr/bin/mailgraph.pl
DAEMON=/usr/bin/mailgraph.pl
MAIL_LOG=/var/log/mail.log
PIDFILE=/var/run/mailgraph.pid
RRD_DIR=/var/lib
ARGS="-d --daemon-pid=$PIDFILE --daemon-rrd=$RRD_DIR -l $MAIL_LOG"

RETVAL=0

do_start() {
      echo -n "Starting $NAME "
      nice -19 $DAEMON $ARGS
      RETVAL=$?
}
do_stop() {
      echo -n "Stopping $NAME "
        start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
        RETVAL="$?"
        [ "$RETVAL" = 2 ] && return 2
        start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
        kill `cat $PIDFILE`
        rm -f $PIDFILE
        return "$RETVAL"
}

case "$1" in
    start)
      do_start
  ;;
    stop)
      do_stop
  ;;
    restart)
      do_stop
      do_start
  ;;
    *)
      echo "Usage: $NAME {start|stop|restart}"
      exit 1
  ;;
esac
exit $RETVAL
